config/routes.rb
Rails.application.routes.draw do

  root 'flights#index'
  resources :flights
  resources :bookings
  resources :passengers
end

app/models/airport.rb
class Airport < ApplicationRecord

  has_many :landings, foreign_key: 'to_id', class_name: 'Flight'
  has_many :takeoffs, foreign_key: 'from_id', class_name: 'Flight'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord

belongs_to :flight
belongs_to :passenger

accepts_nested_attributes_for :passenger

end

app/models/flight.rb
class Flight < ApplicationRecord

  has_one :from, class_name: 'Airport'
  has_one :to, class_name: 'Airport'
  has_many :bookings, foreign_key: 'flight_id', class_name: 'Booking'
  has_many :passengers, through: :bookings



end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :bookings
  has_many :flights, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @pas_number = params[:booking][:num_of_p].to_i
    @booking = Booking.new(flight_id: params[:booking][:flight_id])
    @flight = Flight.find(params[:booking][:flight_id])
    @from_airport = Airport.find(@flight.from_id)
    @to_airport = Airport.find(@flight.to_id)
  end


  def create
    params[:booking][:numb].to_i.times do |i|
      p = Passenger.create(name: params[:booking][:passengers][:"name#{i+1}"], email: params[:booking][:passengers][:"email#{i+1}"])
       @b = Booking.create(flight_id: params[:booking][:flight_id], passenger_id: p.id)
      PassengerMailer.with(p: p).thank_you.deliver_now
    end
    redirect_to booking_path(@b.id)
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = Flight.find(@booking.flight_id)
    @passengers = Passenger.all.where(id: (Booking.all.select(:passenger_id).where(flight_id: @flight.id)))
    @from_airport = Airport.find(@flight.from_id)
    @to_airport = Airport.find(@flight.to_id)
    @pas_number = @passengers.count
  end


  # def passenger_params
  #   params.permit(:flight_id, :num_of_p, passenger_attributes: [:name0, :email0, :name1, :email1, :name2, :email2])
  # end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @dates= Flight.select(:flight_start).pluck(:flight_start).uniq
    @flight = Flight.new
    @airports = Airport.all.map{ |u| [ u.city, u.id ] }
    if params.has_key?(:num_of_p)
      @results = []
      @num_of_p = params[:num_of_p]
      @results = Flight.where("from_id = ? AND to_id = ? AND flight_start = ?", params[:flight][:from_id], params[:flight][:to_id], params[:flight][:flight_start]).limit(3)
    end
  end
#
#
# def params
#   params.require(:flight).permit( :from_id, :to_id, :flight_start)
# end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<center>

  <h1 class="title">Booking for:</h1>
  <h1 class="subtitle">Flight from: <%=" \"#{@from_airport.name}\" (#{@from_airport.city}, #{@from_airport.country} )"%></h1>
  <h1 class="subtitle">Flight to: <%=" \"#{@to_airport.name}\" (#{@to_airport.city}, #{@to_airport.country} )"%></h1>
  <h1 class="subtitle">Date: <%= @flight.flight_start%></h1>
  <h1 class="subtitle">Booking for: <%= pluralize(@pas_number, 'person')%></h1>


<%= form_for @booking do |f| %>
  <%= f.hidden_field :flight_id, :value => @flight.id %>
  <%= f.hidden_field :numb, :value => @pas_number %>

    <% @pas_number.times do |i|%>

      <%= f.fields_for :passengers, @booking.passenger do |pas| %>
    <p class="title">  <%= "Passenger number #{i+1}"%> </p>


        <div class="field">
          <%= pas.label :name, class: "label" %>
          <div class="control">
            <%= pas.text_field  "name#{i+1}", class: "input" %>
          </div>
        </div>

        <div class="field">
          <%= pas.label :email, class: "label" %>
          <div class="control">
            <%= pas.email_field :"email#{i+1}", class: "input" %>
          </div>
        </div>

    <% end %>
  <% end %>
  <%= f.submit "Make reservation"  , class: "button full-size is-info is-medium" %>
<% end %>
</center>

app/views/bookings/show.html.erb
<div class="container">
  <center>
<h1 class="title">Bookings for:</h1> <br>
<h1 class="subtitle">Flight from: <%=" \"#{@from_airport.name}\" (#{@from_airport.city}, #{@from_airport.country} )"%></h1>
<h1 class="subtitle">Flight to: <%=" \"#{@to_airport.name}\" (#{@to_airport.city}, #{@to_airport.country} )"%></h1>
<h1 class="subtitle">Date: <%= @flight.flight_start%></h1>
<h1 class="subtitle">Passenger count: <%= pluralize(@pas_number, 'person')%></h1>

    <br><br>
    <h1 class="title">Passengers:</h1>

<% @passengers.each do |p| %>
      <div class="box">
      <p class="subtitle">Name: <%= p.name %></p>
      <p class="subtitle">Email: <%= p.email %></p>
      </div>
<% end %>

  </center>

</div>

app/views/flights/index.html.erb
<section class="hero is-info is-small">
  <div class="hero-body bpic">
    <center>
    <div class="container">
      <%= form_for(@flight, url: flights_path, method: :get ) do |f| %>
        <%= f.label :from_id, "From:" %>
        <div class="select is-multiple">
          <%= f.select(:from_id, @airports) %>
        </div>
        <%= f.label :to_id, "To:" %>
        <div class="select is-multiple">
          <%= f.select(:to_id, @airports) %>
        </div>
        <%= f.label :flight_start, "Date:" %>
        <div class="select is-multiple">
        <%= f.select :flight_start, @dates%>
        </div>
        <%= label :num_of_p, "Number of passangers:" %>
        <div class="select is-multiple">
          <%= select_tag(:num_of_p, options_for_select([1,2,3,4]))%>
        </div>
       <br> <br> <br>
        <%= submit_tag 'Search', class: "button"%>
      <% end %>




    </div>
    </center>
    <br><br>

    <% unless @results.nil? %>
    <%= form_for(:booking, url: new_booking_path, method: :get) do |f| %>

    <div class="columns">
      <%if ( @results.length.times do |i| %>
       <% a = Airport.find(@results[i].from_id) %>
       <% b = Airport.find(@results[i].to_id) %>
        <div class="column">

          <h1 class="subtitle">From:</h1>
          <p class="title">  <%= a.name + " (#{a.city}, #{a.country})" %> </p>

          <p class="subtitle">To:</p>
          <p class="title">  <%= b.name + " (#{b.city}, #{b.country})" %> </p>

          <p class="subtitle">Flight departure date:</p>
        <p class="title"> <%= @results[i].flight_start %> </p>

          <p class="subtitle">Duration:</p>
        <p class="title"> <%= @results[i].flight_duration.to_s + " hours and #{rand(60)} minutes." %> </p>

         <center> <%= f.radio_button :flight_id, @results[i].id %> </center>

        </div>

      <% end) == 0 %>
        <div class="notification is-warning">
      <%= render plain: "Sorry, but no flight is available for the given criteria."%>
        </div>

        <% end %>
      <%= f.hidden_field :num_of_p, :value => @num_of_p %>
    </div>
      <% unless @results.empty? %>
      <%= f.submit "Pick flight"  , class: "button full-size is-medium" %>
      <% end %>
      <% end %>
      <% end %>


  </div>
</section>

app/views/layouts/_footer.html.erb
<footer class="footer" id="footr">
  <div class="content has-text-centered">
    <p>
      An assignment from <a href="https://www.theodinproject.com">The Odin Project</a>. Completed by <a href="https://github.com/dvik1950">Viktor D.</a>
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar is-info">
<div class="container">
  <%= link_to "Odin Flight Booker", root_path, class: "navbar-item title" %>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odin Flight Booker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="page-content">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  </body>
</html>